---
- name: OpenVPN | package | Install requirement packages
  apt:
    pkg:
      - apt-transport-https
    update_cache: yes

- name: OpenVPN | package | Install requirement packages
  apt:
    pkg:
    - ca-certificates
    - python3-software-properties

- name: OpenVPN | package | Get official OpenVPN APT key
  get_url:
    url: https://swupdate.openvpn.net/repos/repo-public.gpg
    dest: ~/openvpn.gpg

- name: OpenVPN | package | Add the official OpenVPN APT key
  apt_key:
    file: ~/openvpn.gpg
    state: present

- name: OpenVPN | package | Reread ansible_lsb facts
  setup:
    filter: ansible_lsb*

- name: OpenVPN | package | Add the official OpenVPN repository
  apt_repository:
    repo: 'deb https://build.openvpn.net/debian/openvpn/stable {{ ansible_lsb.codename }} main'
    state: present
    update_cache: yes

- name: OpenVPN | package | Install required packages
  apt:
    pkg:
    - sudo
    - python3-pip
    - python3-virtualenv
    - git
    - gawk
    - gnupg
    - iptables
    - wamerican-huge
    - openssl
    - openvpn

- name: OpenVPN | package | Install pexpect via pip
  pip:
    name: "pexpect"
    version: "3.3"
